### ISSUE TITLE
Significant difference between 'repo' and software archive

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/function-documentation#10]
During preparation of the XAR for the upcoming release, I see a significant difference in the file templates/page.html , between the XAR in the public repo (labeled 0.7) and the code in GitHub (labeled 0.6).

any idea? @wolfgangmm  ?

<img width="1663" alt="diff_files" src="https://cloud.githubusercontent.com/assets/1700062/21962715/079c5c32-db2d-11e6-94d9-bad8a8c04171.png">

**Comment by joewiz** [comment]
@dizzzz It appears @wolfgangmm has addressed this in the 0.8 release (now in the public repo at http://demo.exist-db.org/exist/apps/public-repo/packages/fundocs.html). There is still a slight difference - the public repo version has a `.existdb.json` file, whereas this is not present in the git repo.
