### ISSUE TITLE
all functions from http://exist-db.org/xquery/app are missing documentation

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/function-documentation#21]
see [exist-db.org](http://exist-db.org/exist/apps/fundocs/view.html?uri=http://exist-db.org/xquery/app&location=/db/apps/public-repo/modules/app.xql&details=true)

**Comment by joewiz** [comment]
Moved to https://github.com/eXist-db/public-xar-repo/issues/20, since the missing xqdoc documentation in https://github.com/eXist-db/public-xar-repo/blob/master/modules/app.xql is a problem with the public-xar-repo's own module, not the function documentation app itself.
