### ISSUE TITLE
 Could you refresh my memory how to add the "read more" button to an entry in the function documentation?

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/function-documentation#36]
@duncdrum Could you refresh my memory how to add the "read more" button to an entry in the function documentation?

_Originally posted by @line-o in https://github.com/eXist-db/documentation/pull/411#issuecomment-576747080_

**Comment by duncdrum** [comment]
I thought it get created auto-magically when contents are placed in the mathcing `data/docs/$$name$$/` folder?

**Comment by line-o** [comment]
Like a so: https://github.com/eXist-db/function-documentation/blob/master/src/main/xar-resources/data/docs/fn/format-date.md
Thanks!
